spring.application.name=dash_bord
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/dash_bord_1}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:beka2006}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:dtm_super_secret_key_minimum_32_chars_long}
jwt.expiration=${JWT_EXPIRATION:86400000}

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads
